#sample config file for jumpr:
clusters:
- clusterName: cluster-name # the actual name of the EKS cluster in AWS
  clusterNickname: nickname # an additional name by which you'll be able to find the cluster
  awsProfile: profile # name of the profile in your ~/.aws/config that would allow you to access the cluster
  awsRegion: some-where-1 # region where the cluster is located
  awsAccountId: "123456789123" # account id where your cluster is located
  proxy: "http_proxy=127.0.0.1:8080" # (optional) proxy server to reach your clusters control plane endpoint