#sample config file for jumpr:

# one cluster
- clusterName: one-cluster-name # the actual name of the EKS cluster in AWS
  clusterNickname: one-nickname # an additional name by which you'll be able to find the cluster
  awsProfile: profile # name of the profile in your ~/.aws/config that would allow you to access the cluster
  awsRegion: some-where-1 # region where the cluster is located
  awsAccountId: "123456789123" # account Id where your cluster is located

# or multiple clusters
- clusterName: first-cluster-name
  clusterNickname: first-nickname
  awsProfile: profile
  awsRegion: some-where-1
  awsAccountId: "123456789123"
- clusterName: second-cluster-name
  clusterNickname: second-nickname
  awsProfile: profile
  awsRegion: some-where-1
  awsAccountId: "123456789123"